spring.application.name=event-sphere-payment

## Supabase PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.hikari.data-source-properties.prepareThreshold=0
## JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

management.server.port=8083

management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always

jwt.secret-key=${JWT_SECRET_KEY}
auth.service.base-url=http://localhost:8080
event.service.base-url=http://localhost:8081


server.port=8082

debug=true
logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.id.ac.ui.cs.advprog.eventspherepayment=DEBUG




