spring.application.name=event-sphere-payment

## Supabase PostgreSQL Configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
#
## JPA/Hibernate Configuration
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.properties.hibernate.formatsql=true
# H2 Database Configuration
spring.datasource.url=jdbc:h2:mem:eventspheredb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT secret key
jwt.secret-key=${JWT_SECRET_KEY}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8080}
event.service.callback.url=${EVENT_SERVICE_CALLBACK_URL:http//localhost:8081}

server.port=8082