spring.application.name=event-sphere-payment

# Supabase PostgreSQL Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.formatsql=true

# JWT secret key
JWT_SECRET_KEY=secret123456

# Auth service URL (misalnya kamu run di port 8081)
auth.service.url=http://localhost:8081/api

# Event service callback URL (misalnya kamu run event service di port 8082)
event.service.callback.url=http://localhost:8082
