name: Continuous Integration (CI)

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      AUTH_SERVICE_BASE_URL: ${{ secrets.AUTH_SERVICE_BASE_URL }}
      EVENT_SERVICE_BASE_URL: ${{ secrets.EVENT_SERVICE_BASE_URL }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java Toolchain
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - name: Run Unit Tests
        run: mvn test
